apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: container-name
          image: docker.io/your-dockerhub-username/app:latest
          ports:
            - containerPort: 80
