apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://<K8S-API-SERVER>:6443
    certificate-authority-data: <BASE64_ENCODED_CA_CERT>

contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
    namespace: default

current-context: my-context

users:
- name: my-user
  user:
    token: <BEARER_TOKEN>  # Alternatively, use `client-certificate-data` and `client-key-data`
